import React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/app/components/ui/card";
import { Badge } from "@/app/components/ui/badge";
import { Button } from "@/app/components/ui/button";
import { CheckCircle, AlertTriangle, ArrowLeft, Clock, FileText, Phone, Mail, Star, Users, Award } from "lucide-react";
import { motion } from "framer-motion";
import Image from "next/image";

interface AnalysisResult {
  summary: string;
  key_points: string[];
  recommendations: string[];
  legal_areas: string[];
  urgency_level: 'low' | 'medium' | 'high' | 'urgent';
  disclaimer: string;
  recommended_lawyers?: Lawyer[]; // Add this to be generated by LLM
}

interface ConsultationData {
  user_issue: string;
  analysis?: AnalysisResult;
}

interface AnalysisResultsProps {
  consultation: ConsultationData;
  onNewConsultation: () => void;
}

interface Lawyer {
  id: string;
  name: string;
  title: string;
  specializations: string[];
  experience: string;
  rating: number;
  reviewCount: number;
  description: string;
  achievements: string[];
  contactEmail: string;
  contactPhone: string;
  image: string;
}

const urgencyConfig: Record<string, { color: string; icon: React.ComponentType<{ className?: string }> }> = {
  low: { color: "bg-green-100 text-green-800 border-green-200", icon: CheckCircle },
  medium: { color: "bg-yellow-100 text-yellow-800 border-yellow-200", icon: Clock },
  high: { color: "bg-orange-100 text-orange-800 border-orange-200", icon: AlertTriangle },
  urgent: { color: "bg-red-100 text-red-800 border-red-200", icon: AlertTriangle }
};

// Function to get lawyers from analysis (generated by LLM)
const getRecommendedLawyers = (analysis: AnalysisResult): Lawyer[] => {
  return analysis.recommended_lawyers || [];
};

export default function AnalysisResults({ consultation, onNewConsultation }: AnalysisResultsProps) {
  const { analysis } = consultation;
  
  // Get recommended lawyers from LLM-generated analysis
  const recommendedLawyers = analysis ? getRecommendedLawyers(analysis) : [];
  
  // Handle case where analysis is undefined
  if (!analysis) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-blue-50 py-20">
        <div className="max-w-5xl mx-auto px-6">
          <div className="text-center">
            <h1 className="text-2xl font-bold text-slate-900 mb-4">No Analysis Available</h1>
            <p className="text-slate-600 mb-8">The analysis data is not available.</p>
            <Button
              variant="outline"
              onClick={onNewConsultation}
              className="border-slate-300 hover:bg-slate-50"
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              New Consultation
            </Button>
          </div>
        </div>
      </div>
    );
  }
  
  const urgencyInfo = urgencyConfig[analysis.urgency_level] || urgencyConfig.medium;
  const UrgencyIcon = urgencyInfo.icon;

  // Helper function to safely render arrays
  const renderArray = (array: unknown, fallback: string[] = ["No data provided"]): string[] => {
    if (!array || !Array.isArray(array)) return fallback;
    return array.length > 0 ? array as string[] : fallback;
  };

  // Helper function to safely render text
  const renderText = (text: unknown, fallback = "No data provided"): string => {
    return (text as string) || fallback;
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-blue-50 py-20">
      <div className="max-w-5xl mx-auto px-6">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          {/* Header */}
          <div className="flex items-center justify-between mb-8">
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 bg-gradient-to-br from-green-500 to-emerald-600 rounded-xl flex items-center justify-center shadow-lg">
                <CheckCircle className="w-6 h-6 text-white" />
              </div>
              <div>
                <h1 className="text-2xl md:text-3xl font-bold text-slate-900">Legal Analysis Complete</h1>
                <p className="text-slate-600">Wizard insights for your legal matter</p>
              </div>
            </div>
            <Button
              variant="outline"
              onClick={onNewConsultation}
              className="border-slate-300 hover:bg-slate-50"
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              New Consultation
            </Button>
          </div>

          {/* User's Original Question - Prominent Display */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="mb-8"
          >
            <Card className="bg-gradient-to-r from-slate-50 to-blue-50 border-slate-200 shadow-lg">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-xl text-slate-900">
                  <FileText className="w-6 h-6 text-blue-600" />
                  Your Legal Question
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="bg-white p-6 rounded-lg border border-slate-200 shadow-sm">
                  <p className="text-slate-700 text-lg leading-relaxed font-medium">
                    "{renderText(consultation.user_issue)}"
                  </p>
                </div>
              </CardContent>
            </Card>
          </motion.div>

          {/* WIN Your Case - Main Lawyer Section */}
          {recommendedLawyers.length > 0 && (
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="mb-12"
              data-lawyers-section
            >
              <div className="text-center mb-8">
                <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4">
                  🏆 WIN Your Case!
                </h2>
                <p className="text-xl text-slate-600 max-w-3xl mx-auto">
                  These top-rated lawyers can help you achieve success and navigate your case to victory
                </p>
              </div>

              <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mb-8">
                {recommendedLawyers.map((lawyer, index) => (
                  <motion.div
                    key={lawyer.id}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.5, delay: 0.1 * index }}
                  >
                    <Card className="bg-white/90 backdrop-blur-sm border-0 shadow-lg hover:shadow-xl transition-all duration-300 h-full">
                      <CardHeader className="pb-4">
                        <div className="flex items-start gap-4">
                          <div className="w-16 h-16 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center text-white text-xl font-bold flex-shrink-0">
                            {lawyer.name.split(' ').map(n => n[0]).join('')}
                          </div>
                          <div className="flex-1">
                            <h3 className="font-bold text-lg text-slate-900">{lawyer.name}</h3>
                            <p className="text-slate-600 text-sm">{lawyer.title}</p>
                            <div className="flex items-center gap-1 mt-1">
                              <div className="flex">
                                {[...Array(5)].map((_, i) => (
                                  <Star
                                    key={i}
                                    className={`w-4 h-4 ${
                                      i < Math.floor(lawyer.rating)
                                        ? 'text-yellow-400 fill-current'
                                        : 'text-slate-300'
                                    }`}
                                  />
                                ))}
                              </div>
                              <span className="text-sm text-slate-600">
                                {lawyer.rating} ({lawyer.reviewCount} reviews)
                              </span>
                            </div>
                          </div>
                        </div>
                      </CardHeader>

                      <CardContent className="space-y-4">
                        <div>
                          <h4 className="font-semibold text-slate-900 mb-2 flex items-center gap-2">
                            <Award className="w-4 h-4 text-blue-600" />
                            Specializations
                          </h4>
                          <div className="flex flex-wrap gap-1">
                            {lawyer.specializations.slice(0, 3).map((spec, idx) => (
                              <Badge
                                key={idx}
                                variant="secondary"
                                className="text-xs bg-blue-100 text-blue-800 border-blue-200"
                              >
                                {spec}
                              </Badge>
                            ))}
                            {lawyer.specializations.length > 3 && (
                              <Badge variant="secondary" className="text-xs bg-slate-100 text-slate-600">
                                +{lawyer.specializations.length - 3} more
                              </Badge>
                            )}
                          </div>
                        </div>

                        <div>
                          <h4 className="font-semibold text-slate-900 mb-2 flex items-center gap-2">
                            <Users className="w-4 h-4 text-green-600" />
                            How I Can Help You WIN
                          </h4>
                          <p className="text-slate-700 text-sm leading-relaxed">
                            {lawyer.description}
                          </p>
                        </div>

                        <div className="border-t pt-4">
                          <div className="flex items-center justify-between text-sm text-slate-600 mb-3">
                            <span className="flex items-center gap-1">
                              <Clock className="w-4 h-4" />
                              {lawyer.experience}
                            </span>
                            <span className="flex items-center gap-1">
                              <CheckCircle className="w-4 h-4 text-green-600" />
                              {lawyer.achievements.length} Awards
                            </span>
                          </div>

                          <div className="space-y-2">
                            <Button 
                              className="w-full bg-gradient-to-r from-green-600 to-green-700 hover:from-green-700 hover:to-green-800 text-white border-0 font-semibold"
                              size="sm"
                            >
                              <Phone className="w-4 h-4 mr-2" />
                              Get FREE Consultation
                            </Button>
                            <Button 
                              variant="outline" 
                              className="w-full border-slate-300 hover:bg-slate-50 text-slate-700"
                              size="sm"
                            >
                              <Mail className="w-4 h-4 mr-2" />
                              Send Message
                            </Button>
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                  </motion.div>
                ))}
              </div>

              <div className="bg-gradient-to-r from-green-50 to-emerald-50 border border-green-200 rounded-xl p-6 text-center">
                <h3 className="text-xl font-bold text-green-800 mb-2">
                  🎯 Ready to WIN Your Case?
                </h3>
                <p className="text-green-700 mb-4">
                  Don't wait - these lawyers are ready to help you achieve success today!
                </p>
                <Button 
                  size="lg"
                  className="bg-gradient-to-r from-green-600 to-green-700 hover:from-green-700 hover:to-green-800 text-white border-0 font-bold px-8"
                >
                  Schedule Your FREE Consultation Now
                </Button>
              </div>
            </motion.div>
          )}

          {/* Analysis Results - Supporting Information */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.4 }}
            className="space-y-6"
          >
            <div className="text-center mb-6">
              <h2 className="text-2xl font-bold text-slate-900 mb-2">Legal Analysis Details</h2>
              <p className="text-slate-600">Detailed breakdown of your legal situation</p>
            </div>

            <div className="grid lg:grid-cols-2 gap-6">
              {/* Summary */}
              <Card className="bg-white/80 backdrop-blur-sm border-0 shadow-lg">
                <CardHeader className="pb-4">
                  <div className="flex items-center justify-between">
                    <CardTitle className="flex items-center gap-2 text-xl">
                      <Image 
                        src="/images/ai_law_wizard_logo.svg" 
                        alt="AI Law Wizard" 
                        width={20} 
                        height={20}
                        className="w-5 h-5 flex-shrink-0"
                      />
                      Case Summary
                    </CardTitle>
                    <Badge className={`${urgencyInfo.color} border flex items-center gap-1`}>
                      <UrgencyIcon className="w-3 h-3" />
                      {renderText(analysis.urgency_level, "medium").charAt(0).toUpperCase() + renderText(analysis.urgency_level, "medium").slice(1)} Priority
                    </Badge>
                  </div>
                </CardHeader>
                <CardContent>
                  <p className="text-slate-700 leading-relaxed">
                    {renderText(analysis.summary)}
                  </p>
                </CardContent>
              </Card>

              {/* Legal Areas */}
              <Card className="bg-white/80 backdrop-blur-sm border-0 shadow-lg">
                <CardHeader>
                  <CardTitle className="text-lg">Areas of Law Identified</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="flex flex-wrap gap-2">
                    {renderArray(analysis.legal_areas).map((area, index) => (
                      <Badge
                        key={index}
                        variant="secondary"
                        className="bg-blue-100 text-blue-800 border-blue-200"
                      >
                        {area}
                      </Badge>
                    ))}
                  </div>
                </CardContent>
              </Card>
            </div>

            {/* Key Points */}
              <Card className="bg-white/80 backdrop-blur-sm border-0 shadow-lg">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <FileText className="w-5 h-5 text-slate-700" />
                    Key Legal Points
                  </CardTitle>
                </CardHeader>
                <CardContent>
                <div className="grid md:grid-cols-2 gap-4">
                    {renderArray(analysis.key_points).map((point, index) => (
                      <div
                        key={index}
                        className="flex gap-3 p-4 bg-slate-50 rounded-lg border border-slate-200"
                      >
                        <div className="w-6 h-6 bg-slate-200 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">
                          <span className="text-xs font-semibold text-slate-600">{index + 1}</span>
                        </div>
                        <p className="text-slate-700 leading-relaxed">{point}</p>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>

              {/* Recommendations */}
              <Card className="bg-white/80 backdrop-blur-sm border-0 shadow-lg">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <CheckCircle className="w-5 h-5 text-green-600" />
                    Recommended Actions
                  </CardTitle>
                </CardHeader>
                <CardContent>
                <div className="grid md:grid-cols-2 gap-3">
                    {renderArray(analysis.recommendations).map((recommendation, index) => (
                      <div
                        key={index}
                        className="flex gap-3 items-start"
                      >
                        <div className="w-2 h-2 bg-green-500 rounded-full mt-2 flex-shrink-0" />
                        <p className="text-slate-700 leading-relaxed">{recommendation}</p>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>

            {/* Final Call to Action */}
            {recommendedLawyers.length > 0 && (
              <Card className="bg-gradient-to-r from-blue-600 to-purple-600 text-white border-0 shadow-xl">
                <CardContent className="text-center py-8">
                  <h3 className="text-2xl font-bold mb-4">Ready to Take Action on Your Case?</h3>
                  <p className="text-blue-100 mb-6 text-lg">
                    Don't let legal issues hold you back. Our recommended lawyers are standing by to help you WIN!
                  </p>
                  <Button 
                    size="lg"
                    className="bg-white text-blue-600 hover:bg-blue-50 border-0 font-bold px-8 py-3"
                    onClick={() => {
                      // Scroll back to lawyers section
                      const lawyersSection = document.querySelector('[data-lawyers-section]');
                      if (lawyersSection) {
                        lawyersSection.scrollIntoView({ behavior: 'smooth' });
                      }
                    }}
                  >
                    Connect with Top Lawyers Now
                  </Button>
                </CardContent>
              </Card>
            )}
          </motion.div>

        </motion.div>
      </div>
    </div>
  );
}